import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface BashTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a bash shell function that acts as a CLI dispatcher.
 */
export function generateBashFunction(options: BashTemplateOptions): string {
  const { name, dirs } = options;
  const dirsArray = dirs.map((d) => `"${d}"`).join(" ");
  const extProbe = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by rc — https://github.com/rodrigopsasaki/rodrigos-cli

function ${name}() {
  local __rc_dirs=(${dirsArray})
  local __rc_name="${name}"

  case "\$1" in
    help|doctor|completions|create)
      local -a __rc_dir_flags=(); for __rc_d in "\${__rc_dirs[@]}"; do __rc_dir_flags+=(--dir "\$__rc_d"); done
      command rc "\$1" --name "\$__rc_name" "\${__rc_dir_flags[@]}"
      return \$?
      ;;
    "")
      local -a __rc_dir_flags=(); for __rc_d in "\${__rc_dirs[@]}"; do __rc_dir_flags+=(--dir "\$__rc_d"); done
      command rc help --name "\$__rc_name" "\${__rc_dir_flags[@]}"
      return \$?
      ;;
  esac

  local __rc_exts=(${extProbe})
  local __rc_script="" __rc_dir="" __rc_depth=0
  local __rc_argc=\$#
  local __rc_args=("\$@")
  local __rc_found=0

  for __rc_d in "\${__rc_dirs[@]}"; do
    for (( __rc_i=__rc_argc; __rc_i>=1; __rc_i-- )); do
      local __rc_path="\$__rc_d"
      local __rc_ok=1

      for (( __rc_j=0; __rc_j<__rc_i-1; __rc_j++ )); do
        __rc_path="\$__rc_path/\${__rc_args[\$__rc_j]}"
        if [[ ! -d "\$__rc_path" ]]; then
          __rc_ok=0
          break
        fi
      done
      [[ \$__rc_ok -eq 0 ]] && continue

      local __rc_leaf="\${__rc_args[\$(( __rc_i - 1 ))]}"
      local __rc_base="\$__rc_path/\$__rc_leaf"

      for __rc_ext in "\${__rc_exts[@]}"; do
        if [[ -f "\$__rc_base.\$__rc_ext" ]]; then
          __rc_script="\$__rc_base.\$__rc_ext"
          __rc_dir="\$__rc_d"
          __rc_depth=\$__rc_i
          __rc_found=1
          break 3
        fi
      done

      if [[ -f "\$__rc_base" && ! -d "\$__rc_base" ]]; then
        __rc_script="\$__rc_base"
        __rc_dir="\$__rc_d"
        __rc_depth=\$__rc_i
        __rc_found=1
        break 2
      fi
    done
  done

  if [[ \$__rc_found -eq 0 ]]; then
    echo "\$__rc_name: command not found: \$*" >&2
    echo "Run '\$__rc_name help' to see available commands." >&2
    return 127
  fi

  local __rc_runner="" __rc_runner_args=""
  case "\$__rc_script" in
    *.sh|*.bash) __rc_runner="bash" ;;
    *.zsh)       __rc_runner="zsh" ;;
    *.py)        __rc_runner="python3" ;;
    *.rb)        __rc_runner="ruby" ;;
    *.js)        __rc_runner="node" ;;
    *.ts)        __rc_runner="npx" __rc_runner_args="tsx" ;;
    *.php)       __rc_runner="php" ;;
    *.pl)        __rc_runner="perl" ;;
    *)
      local __rc_shebang
      __rc_shebang=\$(head -1 "\$__rc_script" 2>/dev/null)
      if [[ "\$__rc_shebang" == "#!/usr/bin/env "* ]]; then
        __rc_runner="\${__rc_shebang#\\#\\!/usr/bin/env }"
        __rc_runner="\${__rc_runner%% *}"
      elif [[ "\$__rc_shebang" == "#!"* ]]; then
        __rc_runner="\${__rc_shebang#\\#\\!}"
        __rc_runner="\${__rc_runner## }"
        __rc_runner="\${__rc_runner##*/}"
        __rc_runner="\${__rc_runner%% *}"
      else
        __rc_runner="bash"
      fi
      ;;
  esac

  local __rc_remaining=("\${__rc_args[@]:\$__rc_depth}")
  local __rc_cmd="\${__rc_args[*]:0:\$__rc_depth}"
  local __rc_all_dirs
  __rc_all_dirs=\$(IFS=:; echo "\${__rc_dirs[*]}")

  RC_COMMAND="\$__rc_cmd" \\
  RC_CLI_NAME="\$__rc_name" \\
  RC_SCRIPT_PATH="\$__rc_script" \\
  RC_DIR="\$__rc_dir" \\
  RC_DIRS="\$__rc_all_dirs" \\
  \$__rc_runner \${__rc_runner_args:+"\$__rc_runner_args"} "\$__rc_script" "\${__rc_remaining[@]}"
}
`;
}
