import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface FishTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a fish shell function that acts as a CLI dispatcher.
 */
export function generateFishFunction(options: FishTemplateOptions): string {
  const { name, dirs } = options;
  const dirsDecl = dirs.map((d) => `"${d}"`).join(" ");
  const extList = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by rc — https://github.com/rodrigopsasaki/rodrigos-cli

function ${name}
  set -l __rc_dirs ${dirsDecl}
  set -l __rc_name "${name}"

  switch "$argv[1]"
    case help doctor completions create
      set -l dir_flags
      for d in $__rc_dirs; set -a dir_flags --dir $d; end
      command rc $argv[1] --name $__rc_name $dir_flags
      return $status
    case ""
      set -l dir_flags
      for d in $__rc_dirs; set -a dir_flags --dir $d; end
      command rc help --name $__rc_name $dir_flags
      return $status
  end

  set -l __rc_exts ${extList}
  set -l __rc_script ""
  set -l __rc_dir ""
  set -l __rc_depth 0
  set -l __rc_argc (count $argv)

  for __rc_d in $__rc_dirs
    for __rc_i in (seq $__rc_argc -1 1)
      set -l __rc_path "$__rc_d"
      set -l __rc_ok 1

      for __rc_j in (seq 1 (math "$__rc_i - 1"))
        set __rc_path "$__rc_path/$argv[$__rc_j]"
        if not test -d "$__rc_path"
          set __rc_ok 0
          break
        end
      end
      test $__rc_ok -eq 0; and continue

      set -l __rc_base "$__rc_path/$argv[$__rc_i]"

      for __rc_ext in $__rc_exts
        if test -f "$__rc_base.$__rc_ext"
          set __rc_script "$__rc_base.$__rc_ext"
          set __rc_dir "$__rc_d"
          set __rc_depth $__rc_i
          break
        end
      end
      test -n "$__rc_script"; and break

      if test -f "$__rc_base"; and not test -d "$__rc_base"
        set __rc_script "$__rc_base"
        set __rc_dir "$__rc_d"
        set __rc_depth $__rc_i
        break
      end
    end
    test -n "$__rc_script"; and break
  end

  if test -z "$__rc_script"
    echo "$__rc_name: command not found: $argv" >&2
    echo "Run '$__rc_name help' to see available commands." >&2
    return 127
  end

  set -l __rc_runner ""
  set -l __rc_runner_args
  switch "$__rc_script"
    case "*.sh" "*.bash"; set __rc_runner bash
    case "*.zsh";         set __rc_runner zsh
    case "*.py";          set __rc_runner python3
    case "*.rb";          set __rc_runner ruby
    case "*.js";          set __rc_runner node
    case "*.ts";          set __rc_runner npx; set __rc_runner_args tsx
    case "*.php";         set __rc_runner php
    case "*.pl";          set __rc_runner perl
    case "*"
      set -l __rc_shebang (head -1 "$__rc_script" 2>/dev/null)
      if string match -q "#!/usr/bin/env *" "$__rc_shebang"
        set __rc_runner (string replace "#!/usr/bin/env " "" "$__rc_shebang" | string split " ")[1]
      else if string match -q "#!*" "$__rc_shebang"
        set __rc_runner (basename (string replace "#!" "" "$__rc_shebang" | string trim | string split " ")[1])
      else
        set __rc_runner bash
      end
  end

  set -l __rc_remaining
  if test $__rc_depth -lt $__rc_argc
    set __rc_remaining $argv[(math "$__rc_depth + 1")..$__rc_argc]
  end
  set -l __rc_cmd (string join " " $argv[1..$__rc_depth])

  set -x RC_COMMAND "$__rc_cmd"
  set -x RC_CLI_NAME "$__rc_name"
  set -x RC_SCRIPT_PATH "$__rc_script"
  set -x RC_DIR "$__rc_dir"
  set -x RC_DIRS (string join ":" $__rc_dirs)

  $__rc_runner $__rc_runner_args "$__rc_script" $__rc_remaining
  set -l __rc_status $status

  set -e RC_COMMAND RC_CLI_NAME RC_SCRIPT_PATH RC_DIR RC_DIRS
  return $__rc_status
end
`;
}
