import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface FishTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
  readonly allowBinaries: boolean;
}

/**
 * Generate a fish shell function that acts as a CLI dispatcher.
 */
export function generateFishFunction(options: FishTemplateOptions): string {
  const { name, dirs, allowBinaries } = options;
  const dirsDecl = dirs.map((d) => `"${d}"`).join(" ");
  const extList = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");
  const defaultAllowBinaries = allowBinaries ? "1" : "0";

  return `# Generated by runic — https://github.com/rodrigopsasaki/runic

function ${name}
  set -l __runic_dirs ${dirsDecl}
  set -l __runic_name "${name}"
  # Default from init flag; override per-call with \`__runic_allow_binaries=1 ${name} ...\`
  if not set -q __runic_allow_binaries
    set __runic_allow_binaries ${defaultAllowBinaries}
  end

  switch "$argv[1]"
    case help doctor runtimes completions create
      set -l dir_flags
      for d in $__runic_dirs; set -a dir_flags --dir $d; end
      set -l extra
      test "$__runic_allow_binaries" = "1"; and set extra --allow-binaries
      command runic $argv[1] --name $__runic_name $dir_flags $extra
      return $status
    case ""
      set -l dir_flags
      for d in $__runic_dirs; set -a dir_flags --dir $d; end
      set -l extra
      test "$__runic_allow_binaries" = "1"; and set extra --allow-binaries
      command runic help --name $__runic_name $dir_flags $extra
      return $status
  end

  set -l __runic_exts ${extList}
  set -l __runic_script ""
  set -l __runic_dir ""
  set -l __runic_depth 0
  set -l __runic_argc (count $argv)

  for __runic_d in $__runic_dirs
    for __runic_i in (seq $__runic_argc -1 1)
      set -l __runic_path "$__runic_d"
      set -l __runic_ok 1

      for __runic_j in (seq 1 (math "$__runic_i - 1"))
        set __runic_path "$__runic_path/$argv[$__runic_j]"
        if not test -d "$__runic_path"
          set __runic_ok 0
          break
        end
      end
      test $__runic_ok -eq 0; and continue

      set -l __runic_base "$__runic_path/$argv[$__runic_i]"

      for __runic_ext in $__runic_exts
        if test -f "$__runic_base.$__runic_ext"
          set __runic_script "$__runic_base.$__runic_ext"
          set __runic_dir "$__runic_d"
          set __runic_depth $__runic_i
          break
        end
      end
      test -n "$__runic_script"; and break

      if test -f "$__runic_base"; and not test -d "$__runic_base"
        # Extensionless: require shebang OR (with binaries allowed) executable bit
        if test (head -c 2 "$__runic_base" 2>/dev/null) = "#!"
          set __runic_script "$__runic_base"
          set __runic_dir "$__runic_d"
          set __runic_depth $__runic_i
          break
        else if test "$__runic_allow_binaries" = "1"; and test -x "$__runic_base"
          set __runic_script "$__runic_base"
          set __runic_dir "$__runic_d"
          set __runic_depth $__runic_i
          break
        end
      end
    end
    test -n "$__runic_script"; and break
  end

  if test -z "$__runic_script"
    echo "$__runic_name: command not found: $argv" >&2
    echo "Run '$__runic_name help' to see available commands." >&2
    return 127
  end

  set -l __runic_runner ""
  set -l __runic_runner_args
  switch "$__runic_script"
    case "*.sh" "*.bash"; set __runic_runner bash
    case "*.zsh";         set __runic_runner zsh
    case "*.py";          set __runic_runner python3
    case "*.rb";          set __runic_runner ruby
    case "*.js";          set __runic_runner node
    case "*.ts";          set __runic_runner npx; set __runic_runner_args tsx
    case "*.php";         set __runic_runner php
    case "*.pl";          set __runic_runner perl
    case "*"
      set -l __runic_shebang (head -1 "$__runic_script" 2>/dev/null)
      if string match -q "#!/usr/bin/env *" "$__runic_shebang"
        set -l __runic_parts (string replace "#!/usr/bin/env " "" "$__runic_shebang" | string split " ")
        for __runic_part in $__runic_parts
          if string match -q -- "-*" "$__runic_part"
            continue
          end
          set __runic_runner $__runic_part
          break
        end
      else if string match -q "#!*" "$__runic_shebang"
        set __runic_runner (basename (string replace "#!" "" "$__runic_shebang" | string trim | string split " ")[1])
      else if test "$__runic_allow_binaries" = "1"
        # No shebang, binaries allowed: exec directly, no runner.
        set __runic_runner ""
      else
        set __runic_runner bash
      end
  end

  set -l __runic_remaining
  if test $__runic_depth -lt $__runic_argc
    set __runic_remaining $argv[(math "$__runic_depth + 1")..$__runic_argc]
  end
  set -l __runic_cmd (string join " " $argv[1..$__runic_depth])

  set -x RUNIC_COMMAND "$__runic_cmd"
  set -x RUNIC_CLI_NAME "$__runic_name"
  set -x RUNIC_SCRIPT_PATH "$__runic_script"
  set -x RUNIC_DIR "$__runic_dir"
  set -x RUNIC_DIRS (string join ":" $__runic_dirs)

  if test -z "$__runic_runner"
    "$__runic_script" $__runic_remaining
  else
    $__runic_runner $__runic_runner_args "$__runic_script" $__runic_remaining
  end
  set -l __runic_status $status

  set -e RUNIC_COMMAND RUNIC_CLI_NAME RUNIC_SCRIPT_PATH RUNIC_DIR RUNIC_DIRS
  return $__runic_status
end
`;
}
