import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface ZshTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a zsh shell function that acts as a CLI dispatcher.
 * The function does greedy longest-match against the filesystem,
 * auto-detects runners from file extensions, and sets RC_* env vars.
 */
export function generateZshFunction(options: ZshTemplateOptions): string {
  const { name, dirs } = options;
  const dirsArray = dirs.map((d) => `"${d}"`).join(" ");
  const extProbe = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by rc — https://github.com/rodrigopsasaki/rodrigos-cli
# eval "$(rc init zsh --name ${name} ${dirs.map((d) => `--dir ${d}`).join(" ")})"

function ${name}() {
  local -a __rc_dirs=(${dirsArray})
  local __rc_name="${name}"

  # Built-in commands delegate to the rc binary
  case "\$1" in
    help|doctor|completions|create)
      local -a __rc_dir_flags=(); for __rc_d in "\${__rc_dirs[@]}"; do __rc_dir_flags+=(--dir "\$__rc_d"); done
      command rc "\$1" --name "\$__rc_name" "\${__rc_dir_flags[@]}"
      return \$?
      ;;
    "")
      local -a __rc_dir_flags=(); for __rc_d in "\${__rc_dirs[@]}"; do __rc_dir_flags+=(--dir "\$__rc_d"); done
      command rc help --name "\$__rc_name" "\${__rc_dir_flags[@]}"
      return \$?
      ;;
  esac

  local -a __rc_exts=(${extProbe})
  local __rc_script="" __rc_dir="" __rc_depth=0

  for __rc_d in "\${__rc_dirs[@]}"; do
    local __rc_max=\$#

    # Greedy: try longest match first (deepest path), then shorter
    for (( __rc_i=__rc_max; __rc_i>=1; __rc_i-- )); do
      local __rc_path="\$__rc_d"
      local __rc_ok=1

      # Build directory path from segments 1..(i-1)
      for (( __rc_j=1; __rc_j<__rc_i; __rc_j++ )); do
        __rc_path="\$__rc_path/\${(P)__rc_j}"
        if [[ ! -d "\$__rc_path" ]]; then
          __rc_ok=0
          break
        fi
      done
      [[ \$__rc_ok -eq 0 ]] && continue

      # Try the i-th argument as a script file (with each known extension)
      local __rc_leaf="\${(P)__rc_i}"
      local __rc_base="\$__rc_path/\$__rc_leaf"

      for __rc_ext in "\${__rc_exts[@]}"; do
        if [[ -f "\$__rc_base.\$__rc_ext" ]]; then
          __rc_script="\$__rc_base.\$__rc_ext"
          __rc_dir="\$__rc_d"
          __rc_depth=\$__rc_i
          break 3
        fi
      done

      # Try extensionless file
      if [[ -f "\$__rc_base" && ! -d "\$__rc_base" ]]; then
        __rc_script="\$__rc_base"
        __rc_dir="\$__rc_d"
        __rc_depth=\$__rc_i
        break 2
      fi
    done
  done

  if [[ -z "\$__rc_script" ]]; then
    echo "\$__rc_name: command not found: \$*" >&2
    echo "Run '\$__rc_name help' to see available commands." >&2
    return 127
  fi

  # Determine runner from file extension
  local __rc_runner="" __rc_runner_args=""
  case "\$__rc_script" in
    *.sh|*.bash) __rc_runner="bash" ;;
    *.zsh)       __rc_runner="zsh" ;;
    *.py)        __rc_runner="python3" ;;
    *.rb)        __rc_runner="ruby" ;;
    *.js)        __rc_runner="node" ;;
    *.ts)        __rc_runner="npx" __rc_runner_args="tsx" ;;
    *.php)       __rc_runner="php" ;;
    *.pl)        __rc_runner="perl" ;;
    *)
      # Read shebang for extensionless files
      local __rc_shebang
      __rc_shebang=\$(head -1 "\$__rc_script" 2>/dev/null)
      if [[ "\$__rc_shebang" == "#!/usr/bin/env "* ]]; then
        __rc_runner="\${__rc_shebang#\\#\\!/usr/bin/env }"
        __rc_runner="\${__rc_runner%% *}"
      elif [[ "\$__rc_shebang" == "#!"* ]]; then
        __rc_runner="\${__rc_shebang#\\#\\!}"
        __rc_runner="\${__rc_runner## }"
        __rc_runner="\${__rc_runner##*/}"
        __rc_runner="\${__rc_runner%% *}"
      else
        __rc_runner="bash"
      fi
      ;;
  esac

  # Build the remaining args (everything after the matched command segments)
  local -a __rc_remaining=("\${@:$(( __rc_depth + 1 ))}")
  local __rc_cmd="\${*:1:\$__rc_depth}"

  # Execute with RC_* environment variables
  RC_COMMAND="\$__rc_cmd" \\
  RC_CLI_NAME="\$__rc_name" \\
  RC_SCRIPT_PATH="\$__rc_script" \\
  RC_DIR="\$__rc_dir" \\
  RC_DIRS="\${(j.:.)__rc_dirs}" \\
  "\$__rc_runner" \${__rc_runner_args:+"\$__rc_runner_args"} "\$__rc_script" "\${__rc_remaining[@]}"
}
`;
}
