import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface ZshTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a zsh shell function that acts as a CLI dispatcher.
 * The function does greedy longest-match against the filesystem,
 * auto-detects runners from file extensions, and sets RUNIC_* env vars.
 */
export function generateZshFunction(options: ZshTemplateOptions): string {
  const { name, dirs } = options;
  const dirsArray = dirs.map((d) => `"${d}"`).join(" ");
  const extProbe = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by runic — https://github.com/rodrigopsasaki/runic
# eval "$(runic init zsh --name ${name} ${dirs.map((d) => `--dir ${d}`).join(" ")})"

function ${name}() {
  local -a __runic_dirs=(${dirsArray})
  local __runic_name="${name}"

  # Built-in commands delegate to the runic binary
  case "\$1" in
    help|doctor|completions|create)
      local -a __runic_dir_flags=(); for __runic_d in "\${__runic_dirs[@]}"; do __runic_dir_flags+=(--dir "\$__runic_d"); done
      command runic "\$1" --name "\$__runic_name" "\${__runic_dir_flags[@]}"
      return \$?
      ;;
    "")
      local -a __runic_dir_flags=(); for __runic_d in "\${__runic_dirs[@]}"; do __runic_dir_flags+=(--dir "\$__runic_d"); done
      command runic help --name "\$__runic_name" "\${__runic_dir_flags[@]}"
      return \$?
      ;;
  esac

  local -a __runic_exts=(${extProbe})
  local __runic_script="" __runic_dir="" __runic_depth=0

  for __runic_d in "\${__runic_dirs[@]}"; do
    local __runic_max=\$#

    # Greedy: try longest match first (deepest path), then shorter
    for (( __runic_i=__runic_max; __runic_i>=1; __runic_i-- )); do
      local __runic_path="\$__runic_d"
      local __runic_ok=1

      # Build directory path from segments 1..(i-1)
      for (( __runic_j=1; __runic_j<__runic_i; __runic_j++ )); do
        __runic_path="\$__runic_path/\${(P)__runic_j}"
        if [[ ! -d "\$__runic_path" ]]; then
          __runic_ok=0
          break
        fi
      done
      [[ \$__runic_ok -eq 0 ]] && continue

      # Try the i-th argument as a script file (with each known extension)
      local __runic_leaf="\${(P)__runic_i}"
      local __runic_base="\$__runic_path/\$__runic_leaf"

      for __runic_ext in "\${__runic_exts[@]}"; do
        if [[ -f "\$__runic_base.\$__runic_ext" ]]; then
          __runic_script="\$__runic_base.\$__runic_ext"
          __runic_dir="\$__runic_d"
          __runic_depth=\$__runic_i
          break 3
        fi
      done

      # Try extensionless file (require shebang to mirror Node-side scanner)
      if [[ -f "\$__runic_base" && ! -d "\$__runic_base" ]]; then
        if [[ "\$(head -c 2 "\$__runic_base" 2>/dev/null)" == "#!" ]]; then
          __runic_script="\$__runic_base"
          __runic_dir="\$__runic_d"
          __runic_depth=\$__runic_i
          break 2
        fi
      fi
    done
  done

  if [[ -z "\$__runic_script" ]]; then
    echo "\$__runic_name: command not found: \$*" >&2
    echo "Run '\$__runic_name help' to see available commands." >&2
    return 127
  fi

  # Determine runner from file extension
  local __runic_runner="" __runic_runner_args=""
  case "\$__runic_script" in
    *.sh|*.bash) __runic_runner="bash" ;;
    *.zsh)       __runic_runner="zsh" ;;
    *.py)        __runic_runner="python3" ;;
    *.rb)        __runic_runner="ruby" ;;
    *.js)        __runic_runner="node" ;;
    *.ts)        __runic_runner="npx" __runic_runner_args="tsx" ;;
    *.php)       __runic_runner="php" ;;
    *.pl)        __runic_runner="perl" ;;
    *)
      # Read shebang for extensionless files
      local __runic_shebang
      __runic_shebang=\$(head -1 "\$__runic_script" 2>/dev/null)
      if [[ "\$__runic_shebang" == "#!/usr/bin/env "* ]]; then
        # Strip prefix, then skip env flags (-S, -i, -vS, ...)
        local __runic_rest="\${__runic_shebang#\\#\\!/usr/bin/env }"
        while [[ "\$__runic_rest" == -* ]]; do
          __runic_rest="\${__runic_rest#* }"
        done
        __runic_runner="\${__runic_rest%% *}"
      elif [[ "\$__runic_shebang" == "#!"* ]]; then
        __runic_runner="\${__runic_shebang#\\#\\!}"
        __runic_runner="\${__runic_runner## }"
        __runic_runner="\${__runic_runner##*/}"
        __runic_runner="\${__runic_runner%% *}"
      else
        __runic_runner="bash"
      fi
      ;;
  esac

  # Build the remaining args (everything after the matched command segments)
  local -a __runic_remaining=("\${@:$(( __runic_depth + 1 ))}")
  local __runic_cmd="\${*:1:\$__runic_depth}"

  # Execute with RUNIC_* environment variables
  RUNIC_COMMAND="\$__runic_cmd" \\
  RUNIC_CLI_NAME="\$__runic_name" \\
  RUNIC_SCRIPT_PATH="\$__runic_script" \\
  RUNIC_DIR="\$__runic_dir" \\
  RUNIC_DIRS="\${(j.:.)__runic_dirs}" \\
  "\$__runic_runner" \${__runic_runner_args:+"\$__runic_runner_args"} "\$__runic_script" "\${__runic_remaining[@]}"
}
`;
}
